name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Calculate short commit hash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.1'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -Drevision=${{env.COMMIT_SHORT_SHA}} package --file pom.xml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ChickenPlanner.jar
          path: target/chicken_planner-${{env.COMMIT_SHORT_SHA}}.jar